version: "3.7"

services:
  # c.f. https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build: .
    command: bash -c "heroku --version && git --version"

    # FIXME: Build passes on arm64, but fails on amd64...
    platform: linux/amd64
